//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.SME.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.SME.Application.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không được để trống.
        /// </summary>
        public static string Empty_Department {
            get {
                return ResourceManager.GetString("Empty_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID đơn vị không được để trống.
        /// </summary>
        public static string Empty_DepartmentID {
            get {
                return ResourceManager.GetString("Empty_DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống.
        /// </summary>
        public static string Empty_EmployeeCode {
            get {
                return ResourceManager.GetString("Empty_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống.
        /// </summary>
        public static string Empty_FullName {
            get {
                return ResourceManager.GetString("Empty_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string GreaterNow_DateOfBirth {
            get {
                return ResourceManager.GetString("GreaterNow_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string GreaterNow_IdentityIssuedDate {
            get {
                return ResourceManager.GetString("GreaterNow_IdentityIssuedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không hợp lệ.
        /// </summary>
        public static string Invalid_DateOfBirth {
            get {
                return ResourceManager.GetString("Invalid_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu Đơn vị không có trong danh mục.
        /// </summary>
        public static string Invalid_Department {
            get {
                return ResourceManager.GetString("Invalid_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID đơn vị không có trong danh mục.
        /// </summary>
        public static string Invalid_DepartmentID {
            get {
                return ResourceManager.GetString("Invalid_DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        public static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính không hợp lệ.
        /// </summary>
        public static string Invalid_Gender {
            get {
                return ResourceManager.GetString("Invalid_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không hợp lệ.
        /// </summary>
        public static string Invalid_IdentityIssuedDate {
            get {
                return ResourceManager.GetString("Invalid_IdentityIssuedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ không được vượt quá 255 kí tự.
        /// </summary>
        public static string Maxlength_Address {
            get {
                return ResourceManager.GetString("Maxlength_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản ngân hàng không được vượt quá 25 kí tự.
        /// </summary>
        public static string Maxlength_BankAccount {
            get {
                return ResourceManager.GetString("Maxlength_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh ngân hàng không được vượt quá 255 kí tự.
        /// </summary>
        public static string Maxlength_BankBranch {
            get {
                return ResourceManager.GetString("Maxlength_BankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng không được vượt quá 255 kí tự.
        /// </summary>
        public static string Maxlength_BankName {
            get {
                return ResourceManager.GetString("Maxlength_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được vượt quá 100 kí tự.
        /// </summary>
        public static string Maxlength_Email {
            get {
                return ResourceManager.GetString("Maxlength_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được vượt quá 20 kí tự.
        /// </summary>
        public static string Maxlength_EmployeeCode {
            get {
                return ResourceManager.GetString("Maxlength_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được vượt quá 100 kí tự.
        /// </summary>
        public static string Maxlength_FullName {
            get {
                return ResourceManager.GetString("Maxlength_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp căn cước công dân không được vượt quá 255 kí tự.
        /// </summary>
        public static string Maxlength_IdentityIssuedPlace {
            get {
                return ResourceManager.GetString("Maxlength_IdentityIssuedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số căn cước công dân không được vượt quá 25 kí tự.
        /// </summary>
        public static string Maxlength_IdentityNumber {
            get {
                return ResourceManager.GetString("Maxlength_IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cố định không được vượt quá 50 kí tự.
        /// </summary>
        public static string Maxlength_LandlinePhone {
            get {
                return ResourceManager.GetString("Maxlength_LandlinePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại di động không được vượt quá 50 kí tự.
        /// </summary>
        public static string Maxlength_MobilePhone {
            get {
                return ResourceManager.GetString("Maxlength_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh không được vượt quá 100 kí tự.
        /// </summary>
        public static string Maxlength_PositionName {
            get {
                return ResourceManager.GetString("Maxlength_PositionName", resourceCulture);
            }
        }
    }
}
